# Generated by Django 5.1 on 2024-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10),
        ),
    ]
